services:
  tileserver:
    image: maptiler/tileserver-gl:latest
    ports:
      - '8080:8080'
    volumes:
      - ./public/offline/tiles:/data
    command: ['--paths', '/data']
    restart: unless-stopped
