use std::{
    env, fs,
    path::{Path, PathBuf},
    process::ExitCode,
    time::Instant,
};

use chrono::{SecondsFormat, Utc};
use clap::Parser;
use reqwest::StatusCode;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

const ENDPOINT: &str = "https://wedgetail-dynamics.com/sandbox/addtarget";
const API_KEY_ENV: &str = "WEDGETAIL_API_KEY";

#[derive(Clone, Debug, Parser)]
#[command(about = "Safe, opt-in Wedgetail sandbox contract probe")]
struct Args {
    /// Actually submit one target. Omit for a network-free dry run.
    #[arg(long)]
    execute: bool,
    /// Required with --execute; acknowledges exactly one target will be injected.
    #[arg(long)]
    confirm_one_target: bool,
    /// Required with --execute; acknowledges the shared sandbox-wide limit of 10 in-flight targets.
    #[arg(long)]
    ack_shared_capacity_risk: bool,
    #[arg(long, default_value_t = 45.0)]
    azimuth_deg: f64,
    #[arg(long, default_value_t = 15.0)]
    altitude_deg: f64,
    #[arg(long, default_value_t = 1400.0)]
    distance_m: f64,
    #[arg(long, default_value_t = 25.0)]
    speed_m_s: f64,
    #[arg(long, default_value_t = 180.0)]
    direction_deg: f64,
    #[arg(long, default_value = "box_1")]
    box_id: String,
    /// Alphanumeric, at most 20 characters. A timestamped label is generated by default.
    #[arg(long)]
    label: Option<String>,
    /// Sanitized JSON evidence. Parent directory must already exist.
    #[arg(long)]
    output: Option<PathBuf>,
}

#[derive(Clone, Debug, Serialize)]
struct TargetRequest {
    azimuth_d: f64,
    altitude_d: f64,
    distance_m: f64,
    speed_m_s: f64,
    direction_d: f64,
    unix_timestamp: i64,
    box_id: String,
    label: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct Evidence {
    schema: &'static str,
    mode: &'static str,
    endpoint: &'static str,
    started_at: String,
    duration_ms: Option<u128>,
    request: Value,
    response: Option<ResponseEvidence>,
    capacity: CapacityEvidence,
    secret_recorded: bool,
}

#[derive(Debug, Serialize, Deserialize)]
struct ResponseEvidence {
    http_status: u16,
    classification: &'static str,
    body: Value,
}

#[derive(Debug, Serialize, Deserialize)]
struct CapacityEvidence {
    requested_targets: u8,
    documented_shared_limit: u8,
    preflight_count_available: bool,
    risk_acknowledged: bool,
    note: &'static str,
}

fn validate(args: &Args) -> Result<(), String> {
    let finite = [
        args.azimuth_deg,
        args.altitude_deg,
        args.distance_m,
        args.speed_m_s,
        args.direction_deg,
    ]
    .iter()
    .all(|v| v.is_finite());
    if !finite
        || !(0.0..=360.0).contains(&args.azimuth_deg)
        || !(0.0..=90.0).contains(&args.altitude_deg)
        || args.distance_m <= 0.0
        || args.speed_m_s <= 0.0
        || !(0.0..=360.0).contains(&args.direction_deg)
    {
        return Err("target fields are non-finite or outside the documented ranges".into());
    }
    if !matches!(args.box_id.as_str(), "box_1" | "box_2" | "box_3") {
        return Err("box-id must be box_1, box_2, or box_3".into());
    }
    if let Some(label) = &args.label
        && (label.is_empty()
            || label.len() > 20
            || !label.chars().all(|c| c.is_ascii_alphanumeric()))
    {
        return Err("label must be 1-20 ASCII alphanumeric characters".into());
    }
    if args.execute && (!args.confirm_one_target || !args.ack_shared_capacity_risk) {
        return Err(
            "live mode requires --confirm-one-target and --ack-shared-capacity-risk".into(),
        );
    }
    Ok(())
}

fn bounded_body(text: &str, secret: &str) -> Value {
    const LIMIT: usize = 4096;
    let redacted = if secret.is_empty() {
        text.to_owned()
    } else {
        text.replace(secret, "[REDACTED]")
    };
    if let Ok(value) = serde_json::from_str::<Value>(&redacted) {
        return value;
    }
    let mut clean: String = redacted.chars().take(LIMIT).collect();
    if redacted.chars().count() > LIMIT {
        clean.push_str("...[truncated]");
    }
    Value::String(clean)
}

fn validate_output_parent(path: &Path) -> Result<(), String> {
    let parent = path.parent().ok_or("output path is invalid")?;
    // `Path::parent` represents a bare relative filename's parent as an empty
    // path. That means the current directory, which is a valid destination.
    if !parent.as_os_str().is_empty() && !parent.exists() {
        return Err("output parent directory does not exist".into());
    }
    Ok(())
}

fn write_evidence(path: &Path, evidence: &Evidence) -> Result<(), String> {
    validate_output_parent(path)?;
    let encoded = serde_json::to_vec_pretty(evidence).map_err(|e| e.to_string())?;
    fs::write(path, encoded).map_err(|e| e.to_string())
}

async fn run(args: Args) -> Result<Evidence, String> {
    validate(&args)?;
    let now = Utc::now();
    let label = args
        .label
        .clone()
        .unwrap_or_else(|| format!("SNTL{}", now.format("%m%d%H%M%S")));
    let request = TargetRequest {
        azimuth_d: args.azimuth_deg,
        altitude_d: args.altitude_deg,
        distance_m: args.distance_m,
        speed_m_s: args.speed_m_s,
        direction_d: args.direction_deg,
        unix_timestamp: now.timestamp(),
        box_id: args.box_id.clone(),
        label,
    };
    let request_json = serde_json::to_value(&request).map_err(|e| e.to_string())?;
    let mut evidence = Evidence {
        schema: "sentinel.wedgetail-contract-evidence/v1",
        mode: if args.execute { "live" } else { "dry_run" },
        endpoint: ENDPOINT,
        started_at: now.to_rfc3339_opts(SecondsFormat::Millis, true),
        duration_ms: None,
        request: request_json.clone(),
        response: None,
        capacity: CapacityEvidence {
            requested_targets: 1,
            documented_shared_limit: 10,
            preflight_count_available: false,
            risk_acknowledged: args.ack_shared_capacity_risk,
            note: "No documented count/status preflight exists; live submission may return HTTP 429.",
        },
        secret_recorded: false,
    };
    if args.execute {
        let key = env::var(API_KEY_ENV)
            .map_err(|_| format!("{API_KEY_ENV} must be present for live mode"))?;
        if key.trim().is_empty() {
            return Err(format!("{API_KEY_ENV} must not be empty"));
        }
        let started = Instant::now();
        let response = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(10))
            .build()
            .map_err(|e| format!("client setup failed: {e}"))?
            .post(ENDPOINT)
            .header("X-API-Key", &key)
            .json(&request)
            .send()
            .await
            .map_err(|e| format!("ambiguous live transport outcome; do not retry blindly: {e}"))?;
        evidence.duration_ms = Some(started.elapsed().as_millis());
        let status = response.status();
        let body = response
            .text()
            .await
            .map(|v| bounded_body(&v, &key))
            .unwrap_or_else(|_| json!({"body_unavailable": true}));
        evidence.response = Some(ResponseEvidence {
            http_status: status.as_u16(),
            classification: if status == StatusCode::TOO_MANY_REQUESTS {
                "shared_capacity_rejected"
            } else if status.is_success() {
                "submission_accepted_not_intercept_confirmed"
            } else {
                "submission_rejected"
            },
            body,
        });
    }
    if let Some(path) = &args.output {
        write_evidence(path, &evidence)?;
    }
    Ok(evidence)
}

#[tokio::main]
async fn main() -> ExitCode {
    match run(Args::parse()).await {
        Ok(evidence) => {
            println!(
                "{}",
                serde_json::to_string_pretty(&evidence).expect("evidence serializes")
            );
            ExitCode::SUCCESS
        }
        Err(message) => {
            eprintln!("contract harness refused or failed: {message}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dry_args() -> Args {
        Args::try_parse_from(["harness"]).unwrap()
    }

    #[test]
    fn defaults_to_network_free_dry_run() {
        let args = dry_args();
        assert!(!args.execute);
        assert!(validate(&args).is_ok());
    }

    #[test]
    fn live_requires_both_explicit_acknowledgements() {
        let mut args = dry_args();
        args.execute = true;
        assert!(validate(&args).is_err());
        args.confirm_one_target = true;
        assert!(validate(&args).is_err());
        args.ack_shared_capacity_risk = true;
        assert!(validate(&args).is_ok());
    }

    #[test]
    fn rejects_invalid_target_without_network() {
        let mut args = dry_args();
        args.azimuth_deg = 361.0;
        assert!(validate(&args).is_err());
        args.azimuth_deg = 1.0;
        args.label = Some("not-valid".into());
        assert!(validate(&args).is_err());
    }

    #[test]
    fn response_evidence_redacts_key_even_if_peer_echoes_it() {
        let body = bounded_body(r#"{"debug":"secret-value"}"#, "secret-value");
        let encoded = serde_json::to_string(&body).unwrap();
        assert!(!encoded.contains("secret-value"));
        assert!(encoded.contains("REDACTED"));
    }

    #[test]
    fn bare_relative_output_filename_uses_current_directory() {
        assert!(validate_output_parent(&PathBuf::from("dry-run-check.json")).is_ok());
        assert!(validate_output_parent(&PathBuf::from("missing-parent/dry-run.json")).is_err());
    }

    #[tokio::test]
    async fn dry_run_records_one_target_and_no_secret() {
        let evidence = run(dry_args()).await.unwrap();
        assert_eq!(evidence.mode, "dry_run");
        assert_eq!(evidence.capacity.requested_targets, 1);
        assert_eq!(evidence.capacity.documented_shared_limit, 10);
        assert!(!evidence.secret_recorded);
        assert!(evidence.response.is_none());
        let encoded = serde_json::to_string(&evidence).unwrap();
        assert!(!encoded.contains("X-API-Key"));
        assert!(!encoded.contains(API_KEY_ENV));
    }
}
