"""Spec §9 defensive-scenario acceptance criteria at service and API level.

Dataset: frontend/tests/fixtures/simulation/defensive-s9.json (generated by
defensive_scenario.py; fictional, synthetic, NOTIONAL). The replay criterion is
verified at recorded-inspection level only: recorded commands, interaction
events, draws, health transitions and ordering survive a restart. Timeline
replay (seek/playback) is deferred to Phase 7 and is not claimed here.
"""
import copy
import json
import os
import random
import subprocess
import sys
from collections import Counter
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

import defensive_scenario
from app.adapters.simulation_v1.projection import mission_identity
from app.main import create_app
from app.recording.storage_codec import decode_text
from app.simulation import resolver
from app.simulation.policy import NAMESPACE

ROOT = Path(__file__).resolve().parents[2]
DATASET = json.loads((ROOT / "frontend/tests/fixtures/simulation/defensive-s9.json").read_text(encoding="utf-8"))
NEUTRAL_PREFIXES = ("CIV-", "UNK-", "W-")
INELIGIBLE_SUFFIXES = ("-OUT", "-OVER")


def post(client, body):
    return client.post("/api/simulation/v1/commands", content=json.dumps(body))


def run_all(path, dataset=DATASET):
    """Submit every mission's command sequence in order; return raw responses by command ID."""
    responses = {}
    with TestClient(create_app(str(path), False)) as client:
        for mission in dataset["missions"]:
            for body in mission["commands"]:
                response = post(client, body)
                assert response.status_code == 200, response.text
                responses[body["command"]["command_id"]] = response.content
    return responses


def results(raw):
    return json.loads(raw)["results_by_timestamp"]


def drone_rows(body):
    return {at: {row["drone_id"]: row for row in rows} for at, rows in body["samples_by_timestamp"].items()}


@pytest.fixture(scope="module")
def recorded(tmp_path_factory):
    path = tmp_path_factory.mktemp("s9") / "s9.sqlite3"
    return path, run_all(path)


def test_tracked_dataset_is_current_and_exhibits_every_phase():
    rebuilt = defensive_scenario.check(defensive_scenario.build(1))
    assert DATASET == json.loads(json.dumps(rebuilt))
    report = defensive_scenario.phase_report(DATASET)
    for mission in report.values():
        times = sorted(mission["pairs"])
        assert [mission["pairs"][t] > 0 for t in times] == [False, False, True, True, True]
        assert set(mission["zeroed"][times[-1]]) == {"B", "R"}
    for mission in DATASET["missions"]:
        body = mission["commands"][0]
        assert body["calibration_profile"]["evidence_status"] == "NOTIONAL"
        assert {c["command"]["source_mode"] for c in mission["commands"]} == {"SIMULATED"}


@pytest.mark.parametrize("hash_seed", ["0", "20260924"])
def test_identical_results_across_two_clean_runs(recorded, tmp_path, hash_seed):
    """A second clean run in a separate process with its own string-hash seed."""
    _, first = recorded
    env = {**os.environ, "PYTHONHASHSEED": hash_seed, "PYTHONDONTWRITEBYTECODE": "1"}
    out = tmp_path / "second.json"
    subprocess.run([sys.executable, defensive_scenario.__file__, "--responses", str(tmp_path / "second.sqlite3"), str(out)],
                   env=env, cwd=ROOT, capture_output=True, check=True)
    assert json.loads(out.read_bytes()) == {command_id: raw.decode("utf-8") for command_id, raw in first.items()}


def test_no_pair_duplicated_within_a_timestamp(recorded):
    _, responses = recorded
    for raw in responses.values():
        for at, value in results(raw).items():
            pairs = [(i["red_drone_id"], i["blue_drone_id"]) for i in value["interactions"]]
            assert len(pairs) == len(set(pairs)), at
            assert len({i["interaction_id"] for i in value["interactions"]}) == len(pairs), at


@pytest.mark.parametrize("mission", DATASET["missions"], ids=lambda m: m["key"])
def test_boundary_distance_polygon_and_band_cases_are_inclusive(recorded, mission):
    _, responses = recorded
    tag = mission["key"][0].upper()
    start = results(responses[f"S9-{tag}-START"])
    first_contact = sorted(start)[2]
    pairs = {(i["red_drone_id"], i["blue_drone_id"]): i for i in start[first_contact]["interactions"]}
    edge = pairs[(f"R-{tag}-EDGE", f"B-{tag}-EDGE")]  # slanted edge point, exactly 250 m apart
    assert edge["separation_m"] == 250.0
    assert (f"R-{tag}-FLOOR", f"B-{tag}-FLOOR") in pairs  # altitude band minimum
    assert (f"R-{tag}-CEIL", f"B-{tag}-CEIL") in pairs  # altitude band maximum
    assert (f"R-{tag}-APEX", f"B-{tag}-APEX") in pairs  # both on a polygon vertex, 200 m apart
    assert (f"R-{tag}-VERTEX", f"B-{tag}-VERTEX") not in pairs  # 250.001 m: just outside radius
    assert not any(red.endswith(INELIGIBLE_SUFFIXES) for red, _ in pairs)


def shuffled(body, seed, rules_seed=99):
    """Permute every snapshot's drone array; permute rules with one per-run seed.

    The profile body is part of immutable calibration identity (C07/C15), so a
    run keeps one rules order; a different order under the same identity is a
    409 conflict, covered separately below.
    """
    rng = random.Random(seed)
    body = copy.deepcopy(body)
    for rows in body["samples_by_timestamp"].values():
        rng.shuffle(rows)
    random.Random(rules_seed).shuffle(body["calibration_profile"]["rules"])
    return body


def test_input_array_order_does_not_affect_results(recorded, tmp_path):
    _, responses = recorded
    permuted = copy.deepcopy(DATASET)
    for mission in permuted["missions"]:
        mission["commands"] = [shuffled(body, i) for i, body in enumerate(mission["commands"])]
    again = run_all(tmp_path / "permuted.sqlite3", permuted)
    for command_id, raw in responses.items():
        assert json.loads(again[command_id]) == json.loads(raw)


def test_reordered_rules_under_one_profile_identity_are_a_calibration_conflict(tmp_path):
    start, hold = DATASET["missions"][0]["commands"][:2]
    with TestClient(create_app(str(tmp_path / "rules.sqlite3"), False)) as client:
        assert post(client, start).status_code == 200
        reordered = copy.deepcopy(hold)
        reordered["calibration_profile"]["rules"].reverse()
        response = post(client, reordered)
        assert (response.status_code, response.json()["command_ack"]["error_code"]) == (409, "CALIBRATION_ID_CONFLICT")
        assert client.get("/api/simulation/v1/runs").json()[0]["state"] == "RUNNING"


def test_simultaneous_effects_do_not_depend_on_pair_processing_order(monkeypatch):
    ordinary = resolver.candidate_steps
    reversed_timestamps = 0

    def reversed_pairs(request, drones):
        items = list(ordinary(request, drones))
        pairs = [item for item in items if item is not None]
        yield from reversed(pairs)
    for mission in DATASET["missions"]:
        for body in mission["commands"]:
            expected = resolver.resolve_drone_attack_simulation(copy.deepcopy(body))
            monkeypatch.setattr(resolver, "candidate_steps", reversed_pairs)
            reordered = resolver.resolve_drone_attack_simulation(copy.deepcopy(body))
            monkeypatch.setattr(resolver, "candidate_steps", ordinary)
            for at, value in expected["results_by_timestamp"].items():
                other = reordered["results_by_timestamp"][at]
                assert other["drone_health"] == value["drone_health"]
                key = lambda i: (i["red_drone_id"], i["blue_drone_id"])  # noqa: E731
                assert sorted(other["interactions"], key=key) == sorted(value["interactions"], key=key)
                # The reversal really took effect: pairs were processed in the opposite order.
                assert [key(i) for i in other["interactions"]] == [key(i) for i in reversed(value["interactions"])]
                reversed_timestamps += len(value["interactions"]) > 1
                # Every health change is exactly the clamped sum of that drone's applied deltas.
                deltas = Counter()
                for interaction in value["interactions"]:
                    for effect in interaction["effects"]:
                        deltas[effect["subject_drone_id"]] += effect["health_delta"]
                for row in value["drone_health"]:
                    assert row["health_after"] == max(0, min(100, row["health_before"] + deltas[row["drone_id"]]))
    assert reversed_timestamps > 0


def test_neutral_unknown_and_out_of_area_rows_are_unchanged(recorded):
    _, responses = recorded
    checked = 0
    for raw in responses.values():
        for value in results(raw).values():
            for row in value["drone_health"]:
                if row["drone_id"].startswith(NEUTRAL_PREFIXES) or row["drone_id"].endswith(INELIGIBLE_SUFFIXES):
                    assert (row["health_after"], row["status_after"]) == (row["health_before"], "ACTIVE")
                    checked += 1
    assert checked == 90  # 5 neutral/unknown/warning drones x 7 samples + 2 ineligible x 5, both areas


def test_no_dispatch_no_managed_assets_and_no_live_source(recorded, tmp_path):
    path, _ = recorded
    with TestClient(create_app(str(path), False)) as client:
        for mission in DATASET["missions"]:
            mid = mission_identity(mission["missionId"])
            world = client.get(f"/api/missions/{mid}/world").json()
            assert world["assets"] == {} and world["tasks"] == {} and "interactive" not in world
            receipts = client.app.state.service.repository.db.execute(
                "SELECT count(*) FROM command_receipts WHERE mission_id=?", (mid,)).fetchone()[0]
            assert receipts == 0
    live = copy.deepcopy(DATASET["missions"][0]["commands"][0])
    live["mission_id"], live["command"]["source_mode"] = "SYN-S9-LIVE", "LIVE"
    with TestClient(create_app(str(tmp_path / "live.sqlite3"), False)) as client:
        rejected = post(client, live)
        assert rejected.status_code == 422
        assert rejected.json()["command_ack"]["error_path"] == "/command/source_mode"
        assert client.get("/api/simulation/v1/runs").json() == []


@pytest.mark.parametrize("mission", DATASET["missions"], ids=lambda m: m["key"])
def test_hold_resume_abort_idempotency_and_conflicts_follow_section_8(tmp_path, mission):
    start, hold, resume, abort = mission["commands"]
    with TestClient(create_app(str(tmp_path / "lifecycle.sqlite3"), False)) as client:
        assert post(client, start).json()["command_ack"]["run_status"] == "RUNNING"
        early = copy.deepcopy(resume)
        early["command"]["command_id"] += "-EARLY"
        assert post(client, early).json()["command_ack"]["error_code"] == "RUN_NOT_HELD"
        held = post(client, hold).json()
        assert held["command_ack"]["run_status"] == "HELD"
        assert held["results_by_timestamp"] == {} and hold["samples_by_timestamp"]  # samples supplied, no outcomes
        resumed = post(client, resume).json()
        assert resumed["command_ack"]["run_status"] == "RUNNING"
        first = sorted(resumed["results_by_timestamp"])[0]
        corrected = {row["drone_id"] for row in resumed["results_by_timestamp"][first]["drone_health"] if row["state_discontinuity"]}
        assert corrected == {mission["repairedOnResume"]}  # supplied health is authoritative and visible
        later = [row for at in sorted(resumed["results_by_timestamp"])[1:] for row in resumed["results_by_timestamp"][at]["drone_health"]]
        assert not any(row["state_discontinuity"] for row in later)
        assert post(client, abort).json()["command_ack"]["run_status"] == "ABORTED"
        for action, code in (("START", "RUN_TERMINAL"), ("HOLD", "RUN_TERMINAL"), ("RESUME", "RUN_NOT_HELD"), ("ABORT", "RUN_TERMINAL")):
            late = copy.deepcopy({"START": start, "HOLD": hold, "RESUME": resume, "ABORT": abort}[action])
            late["command"]["command_id"] += "-AFTER-ABORT"
            response = post(client, late)
            assert (response.status_code, response.json()["command_ack"]["error_code"]) == (409, code)
        original = post(client, start)
        assert post(client, start).content == original.content  # completed identical retry after ABORT
        altered = copy.deepcopy(start)
        altered["resolution"]["interaction_radius_m"] = 249
        assert post(client, altered).json()["command_ack"]["error_code"] == "COMMAND_ID_CONFLICT"
        run = client.get(f"/api/simulation/v1/runs/{mission_identity(mission['missionId'])}").json()
        assert (run["state"], run["phase"]) == ("ABORTED", "ready")


def frames_by_effective_time(repository, mid):
    recording = repository.recording_for(mid).id
    frames = {}
    for effective_at, stored in repository.db.execute(
            "SELECT effective_at, frame_json FROM frames WHERE recording_id=? ORDER BY sequence", (recording,)):
        frames[effective_at] = json.loads(decode_text(stored))
    return frames


def test_recorded_inspection_retains_ids_draws_transitions_and_order_after_restart(recorded):
    path, responses = recorded
    with TestClient(create_app(str(path), False)) as client:  # a new app instance reopens the database
        for mission in DATASET["missions"]:
            mid = mission_identity(mission["missionId"])
            commands = client.get(f"/api/simulation/v1/runs/{mid}/commands").json()
            assert [c["action"] for c in commands] == ["START", "HOLD", "RESUME", "ABORT"]
            assert {c["state"] for c in commands} == {"completed"}
            for body in mission["commands"]:
                command_id = body["command"]["command_id"]
                stored = client.get("/api/simulation/v1/command-result", params={"command_id": command_id})
                assert stored.content == responses[command_id]
            events, after = [], -1
            while True:
                page = client.get(f"/api/missions/{mid}/events", params={"after": after, "limit": 500}).json()
                events += page["events"]
                if page.get("nextAfter") is None:
                    break
                after = page["nextAfter"]
            recorded_interactions = [(e["effectiveAt"], e["extensions"][NAMESPACE]["result"])
                                     for e in events if e["type"] == "simulation.v1.interaction"]
            expected = [(at, interaction) for body in mission["commands"]
                        for at, value in sorted(results(responses[body["command"]["command_id"]]).items())
                        for interaction in value["interactions"]]
            assert recorded_interactions == expected  # IDs, draws, effects and ordering
            assert [e["sequence"] for e in events] == sorted(e["sequence"] for e in events)
            assert events[-1]["type"] == "simulation.v1.command-completed"
            frames = frames_by_effective_time(client.app.state.service.repository, mid)
            for body in mission["commands"]:
                for at, value in results(responses[body["command"]["command_id"]]).items():
                    entities = {e["label"]: e for e in frames[at]["entities"].values()}
                    for row in value["drone_health"]:
                        detail = entities[row["drone_id"]]["extensions"][NAMESPACE]
                        assert (detail["health"], detail["reportedStatus"]) == (row["health_after"], row["status_after"])
            world = client.get(f"/api/missions/{mid}/world").json()
            assert world["mission"]["lifecycle"] == "completed"


def test_larger_backend_variant_keeps_the_resolver_criteria():
    dataset = defensive_scenario.build(25)  # phase timing is tuned for the UI scale; criteria below are scale-free
    for mission in dataset["missions"]:
        for body in mission["commands"]:
            first = resolver.resolve_drone_attack_simulation(copy.deepcopy(body))
            assert resolver.resolve_drone_attack_simulation(shuffled(body, 7)) == first
            for value in first["results_by_timestamp"].values():
                pairs = [(i["red_drone_id"], i["blue_drone_id"]) for i in value["interactions"]]
                assert len(pairs) == len(set(pairs))
                for row in value["drone_health"]:
                    if row["drone_id"].startswith(NEUTRAL_PREFIXES) or row["drone_id"].endswith(INELIGIBLE_SUFFIXES):
                        assert row["health_after"] == row["health_before"]
        assert sum(len(rows) for rows in mission["commands"][0]["samples_by_timestamp"].values()) > 2000
