import { useState } from 'react'
import { Section } from '@/components/panel/Section'

export function AssistantView() {
  const [input, setInput] = useState('')
  const [messages, setMessages] = useState([{ role: 'assistant', text: 'I can explain current data and prepare a local draft. I cannot run tasks or read raw sensor feeds.' }])
  const send = () => { if (!input.trim()) return; setMessages((items) => [...items, { role: 'user', text: input }, { role: 'assistant', text: 'Draft updated locally. Add the area, duration, connection requirements, and policy reference before review.' }]); setInput('') }
  return <div className="flex flex-col gap-4 p-3"><div className="rounded-sm border border-signal-nominal/30 bg-panel-inset p-2 text-2xs text-signal-nominal">LOCAL DRAFTS ONLY</div><Section title="Assistant"><div className="flex flex-col gap-1.5">{messages.map((message, index) => <div key={index} className={`rounded-sm border p-2 text-xs leading-relaxed ${message.role === 'assistant' ? 'border-border-faint bg-panel-inset text-text-secondary' : 'border-border-strong bg-state-selected text-text'}`}><span className="mb-1 block text-2xs uppercase text-text-tertiary">{message.role}</span>{message.text}</div>)}</div></Section><form onSubmit={(e) => { e.preventDefault(); send() }} className="flex gap-1"><input aria-label="Ask assistant" value={input} onChange={(e) => setInput(e.target.value)} placeholder="Ask about current data…" className="min-w-0 flex-1 rounded-sm border border-border bg-panel-inset px-2 py-1.5 text-xs"/><button className="rounded-sm border border-border px-2 text-2xs">SEND</button></form><Section title="Draft status"><div className="rounded-sm bg-panel-inset p-2 text-2xs text-text-tertiary">LOCAL ONLY · Area missing · Policy reference missing</div></Section></div>
}
