import { useState } from 'react'
import { SENSOR_SOURCES } from '@/data/operations'
import { Section } from '@/components/panel/Section'

export function SensorsView() {
  const [runtime, setRuntime] = useState<Array<{ id: string; type: string; yaw: number }>>([])
  const [type, setType] = useState('Radar')
  return <div className="flex flex-col gap-4 p-3"><Section title="Ingestion health"><div className="grid grid-cols-3 gap-1 text-center"><div className="bg-panel-inset p-1"><strong className="block text-signal-nominal">4</strong><span className="text-2xs">HEALTHY</span></div><div className="bg-panel-inset p-1"><strong className="block text-signal-caution">1</strong><span className="text-2xs">DEGRADED</span></div><div className="bg-panel-inset p-1"><strong className="block text-signal-critical">1</strong><span className="text-2xs">OFFLINE</span></div></div></Section>
    <Section title="Sources"><div className="flex flex-col gap-1">{SENSOR_SOURCES.map((source) => <div key={source.id} className="rounded-sm border border-border-faint bg-panel-inset p-2"><div className="flex justify-between"><strong className="text-xs">{source.name}</strong><span className={source.state === 'nominal' ? 'text-2xs text-signal-nominal' : source.state === 'caution' ? 'text-2xs text-signal-caution' : 'text-2xs text-signal-critical'}>{source.state.toUpperCase()}</span></div><div className="mt-1 flex justify-between font-mono text-2xs text-text-tertiary"><span>{source.id} · {source.product}</span><span>{source.freshness} / {source.delivery}</span></div></div>)}</div></Section>
    <Section title="Runtime training sensors"><div className="flex gap-1"><select value={type} onChange={(e) => setType(e.target.value)} className="min-w-0 flex-1 rounded-sm border border-border bg-panel-inset px-2 text-xs"><option>Radar</option><option>RF</option><option>EO / IR</option><option>Acoustic</option></select><button onClick={() => setRuntime((items) => [...items, { id: `TRN-${items.length + 1}`, type, yaw: 0 }])} className="rounded-sm border border-border px-2 py-1.5 text-2xs">ADD</button></div><div className="mt-2 flex flex-col gap-1">{runtime.map((sensor) => <div key={sensor.id} className="flex items-center justify-between rounded-sm bg-panel-inset p-2 text-2xs"><span>{sensor.id} · {sensor.type} · {sensor.yaw}°</span><span><button onClick={() => setRuntime((items) => items.map((item) => item.id === sensor.id ? { ...item, yaw: item.yaw + 45 } : item))} className="mr-2">+45°</button><button onClick={() => setRuntime((items) => items.filter((item) => item.id !== sensor.id))} className="text-signal-critical">REMOVE</button></span></div>)}</div></Section>
  </div>
}
